# Generated by Django 5.1.4 on 2024-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('monthly_income_bruto', models.IntegerField(default=0)),
                ('monthly_expenses', models.IntegerField(default=0)),
                ('monthly_budget', models.IntegerField(default=0)),
                ('saved_money', models.IntegerField(default=0)),
                ('goals', models.JSONField(default=dict)),
            ],
        ),
    ]
