# Generated by Django 5.1.4 on 2024-12-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userinfo_user_alter_userinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
