# Generated by Django 5.1.4 on 2024-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_goals_goal_rename_transactions_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='monthly_income_bruto',
            new_name='monthly_income_netto',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
