# Generated by Django 5.1.4 on 2025-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_savingsaccountdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='entertainment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='groceries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='others',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savingsaccountdata',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
