# Generated by Django 5.1.4 on 2025-01-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_userinfo_entertainment_userinfo_groceries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='monthly_expenses',
        ),
    ]
