# Generated by Django 5.1.4 on 2025-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_name_goal_description_remove_goal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
