# Generated by Django 5.1.4 on 2025-01-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_goal_completed_goal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
    ]
